laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop','as' => 'shop.'],function(){
		
	Route::get('/sub-categories/{id}', function ($id) {	
		return view('user-panel.sub-categories')->with(['catId' => $id]);
	})->name('our-menu');

	// Route::get('/sub-categories/{id}/{catId}', function ($id, $catId) {
	// 	return view('user-panel.sub-categories')->with(['subId' => $id, 'catId' => $catId]);
	// })->name('sub-menu');
	
	// Route::get('/child-categories/{id}/{subId}/{catId}', function ($id, $subId, $catId) {
	// 	return view('user-panel.child-categories')->with(['childId' => $id, 'subId' => $subId, 'catId' => $catId]);
	// })->name('child-menu');
	
	Route::get('/products/{cat}/{sub?}', 'ProductController@allProducts')->name('products');

	Route::get('/product/{id}','ProductController@show')->name('product');
	
	Route::get('/faq','FaqController@all')->name('faq');

	Route::get('/cart', function () {
		return view('user-panel.cart');
	})->name('cart');

	Route::get('/contact-us', function () {
		return view('user-panel.contact-us');
	})->name('contact');
	// Route::post('/contact', 'HomeController@contact')->name('add.contact');
	Route::get('/detail/{type}', 'HomeController@webDetails')->name('web-detail');

	Route::get('/our-story', function () {
		return view('user-panel.about');
	})->name('about');

	// Route::get('/terms', function () {
	// 	return view('user-panel.terms');
	// });

	Route::get('/search', 'ProductController@search')->name('search');
	
	Route::get('/offers', 'ProductController@offers')->name('offers');

	Route::post('/checkout','OrderController@checkout')->name('checkout');

	Route::post('/placeorder','OrderController@getPay')->name('placeorder');	

	Route::post('/paystatus','OrderController@orderStatus')->name('orderStatus');

	Route::resource('enquiry', 'EnquiryController');
	


	Route::post('fin-pin','PinCodeController@finPincode')->name('find-pin');

	Route::get('custom/{id}','OrderController@custom')->name('custom');
	
	Route::post('custom-enquiry','CustomEnquiryController@store')->name('store.custom');

	Route::get('/booked/order/{id}/{status?}', 'OrderController@previous')->name('previous');

});

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){
	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/form', function() {
		return view('admin.form');
	});
	Route::get('/table', function() {
		return view('admin.table');
	});

	Route::get('fetch-images/{id}','ProductController@images')->name('images');
	Route::resource('product', 'ProductController');
	Route::get('/detail', 'HomeController@view')->name('web-detail.index');
	Route::post('/detail', 'HomeController@update')->name('web-detail');
	
	// Route::resource('flavor', 'FlavorController');
	Route::resource('faq', 'FaqController');
	Route::resource('category', 'CategoryController');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('material', 'MaterialController');
	Route::resource('type-detail', 'TypeDetailController');
	Route::resource('color', 'ColorController');
	// Route::resource('child-category', 'ChildCategoryController');
	// Route::resource('super-child-category', 'SuperChildCategoryController');
	Route::resource('pincode','PinCodeController');	
	// Route::resource('testimonial', 'TestimonialController');
	// Route::resource('client', 'ClientController');
	Route::resource('banner', 'BannerController');
	Route::resource('second-banner', 'SecondBannerController');
	// Route::resource('offer', 'OfferController');
	// Route::resource('occasion', 'OccasionController');
	Route::resource('order', 'OrderController');
	Route::resource('enquiry', 'EnquiryController');
	// Route::resource('custom-enquiry', 'CustomEnquiryController');
	Route::post('send-enquiry', 'EnquiryController@send')->name('enquiry.send');
	// Route::post('send-custom-enquiry', 'CustomEnquiryController@send')->name('custom-enquiry.send');
	
	// Route::get('demo', 'CustomEnquiryController@demo');
	// Route::post('get-product', 'ProductController@getProduct')->name('get-product');
	
	Route::get('sub-categories/{id?}', 'SubCategoryController@getSubCategories')->name('getSubCategories');
	Route::post('fetch-types', 'TypeController@fetchTypes')->name('fetch-types');	
	Route::get('invoice/{id}', 'OrderController@invoice')->name('order-invoice');
	
	Route::get('fetch-all-images','ImportController@images')->name('all-images');	
	Route::get('import/', 'ImportController@import')->name('import-product');
	Route::post('upload-excel/', 'ImportController@uploadFile')->name('upload-excel');
	Route::post('import/', 'ImportController@importData')->name('import');
	Route::get('stock', 'ProductController@stock')->name('stock');
	
});



Route::get('/drop', ['as' => 'upload', 'uses' => 'ImageController@getUpload']);

Route::get('/drop2', function(){
	return view('admin.drop2');
});

Route::get('file-upload', 'JqueryController@index');
Route::post('file-upload', 'JqueryController@store')->name('file-upload');

Route::post('upload', ['as' => 'upload-post', 'uses' =>'ImageController@postUpload']);
Route::post('upload/delete', ['as' => 'upload-remove', 'uses' =>'ImageController@deleteUpload']);

laravel/app/Http/Controllers/UserPanel/ProductController.php
<?php

namespace App\Http\Controllers\UserPanel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/user-panel/layouts/footer.blade.php
<!--footer-->
<div class="footer">
	<div class="container">
		<div class="footer-info">
			<div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".5s">
				<h4 class="footer-logo"><a href="index.html">Little <b>Jamun</b> <span class="tag">Everything for Kids world </span> </a></h4>
				<p>© 2018  Little Jamun Modern Shoppe for Kids . All rights reserved | Design by <a href="http://sungare.com" target="_blank">Sungare Technologies
				</p>
			</div>
			<div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".7s">
				<h3>Popular</h3>
				<ul>
					<li><a href="{{ route('shop.about') }}">About Us</a></li>
					<li><a href="{{ route('shop.contact') }}">Contact Us</a></li>
					<li><a href="{{ route('shop.faq') }}">FAQ</a></li>
				</ul>
			</div>
			<div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".9s">
				<h3>Subscribe</h3>
				<p>Sign Up Now For More Information <br> About Our Company </p>
				<form>
					<input type="text" placeholder="Enter Your Email" required="">
					<input type="submit" value="Go">
				</form>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--//footer-->		
<!--search jQuery-->
<script src="{{ asset('js/main.js') }}"></script>
<!--//search jQuery-->
<!--smooth-scrolling-of-move-up-->
<script type="text/javascript">
	$(document).ready(function() {
		var defaults = {
			containerID: 'toTop',
			containerHoverID: 'toTopHover',
			scrollSpeed: 1200,
			easingType: 'linear' 
		};

		$().UItoTop({ easingType: 'easeOutQuart' });

	});
	simpleCart.currency({
		code: "INR" ,
		symbol: "&#8377;" ,
		name: "Indian Rupees"
	});
	simpleCart.bind('afterAdd', function(item){
		$('html, body').animate({scrollTop : 0},600);    
		$('#cartBox').addClass('blink_me');
		window.setTimeout(function(){
			$('#cartBox').removeClass('blink_me');
		},2000);
	});
	$(window).on('load',function(){
		$('#loader2').addClass('hidden');
	});

	simpleCart.bind( 'update' , function(item){		

		var button = $('.simpleCart_checkout');
		button.hide();       

		var quantity = simpleCart.quantity();

		if(quantity > 0){
			button.show();
		}

		if(quantity == 0){
			button.hide();
		}
	}); 
	// simpleCart.bind( 'beforeAdd' , function( item ){
		// console.log(simpleCart.quantity());
		// if(simpleCart.quantity() > 10 ){
		// 	alert("The maximum number of items per order is 10. Please remove some items and try again.");
		// 	return false;
		// }
	// });
</script>
<!--//smooth-scrolling-of-move-up-->
<!--Bootstrap core JavaScript
	================================================== -->
	<!--Placed at the end of the document so the pages load faster -->
	<script src="{{ asset('js/bootstrap.js') }}"></script>
	<script src="{{ asset('admin-assets/js/custom/common.js') }}"></script>
	@stack('footer')
</body>
</html>

laravel/resources/views/user-panel/layouts/header.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Little Jamun | @yield('title') </title>
	<!-- for-mobile-apps -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Modern Shoppe for Kids" />
	<link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/fav.png') }}">	
	<script type="application/x-javascript"> 
		addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } 
	</script>
	<style type="text/css">
	.loader{
		display: none;
		color: white;  
		height: 1000px;
		font-family: initial;
		position: fixed;
		top: 0;
		font-size: 36px;
		z-index: 9999;
		background: rgba(0, 0, 0, 0.88);
		width: 100%;
		text-align: center;
		padding-top: 250px;
	}
	#loader2{
		display: block;            
		background: #2b0039 !important;
	}
</style>
<!--//for-mobile-apps -->
<!--Custom Theme files -->
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all" />
<link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{{ asset('css/flexslider.css') }}" type="text/css" media="screen" />

<link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">

<!--//Custom Theme files -->
<!--js-->
<script src="{{ asset('js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ asset('js/modernizr.custom.js') }}"></script>
<!--//js-->
<!--cart-->
<script src="{{ asset('js/simpleCart.min.js') }}"></script>
<!--cart-->
<!--web-fonts-->
<link href='//fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'><link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Fascinate' rel='stylesheet' type='text/css'>
<!--web-fonts-->
<!--animation-effect-->
<link href="{{ asset('css/animate.min.css') }}" rel="stylesheet"> 
<script src="{{ asset('js/wow.min.js') }}"></script>
<script>
	new WOW().init();
</script>
<!--//animation-effect-->
<!--start-smooth-scrolling-->
<script type="text/javascript" src="{{ asset('js/move-top.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/easing.js') }}"></script>	
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!--//end-smooth-scrolling-->
@stack('header')
</head>
<body @yield('body')>
	<div class="loader" id = "loader2">
		<img src="{{ asset('images/logo.png') }}" width = "300">
	</div>
	<div class="loader" id = "loader">
		<div>Taking you to Payment Portal, please wait.</div>
	</div>
	<!--header-->
	<div class="header">
		<div class="top-header navbar navbar-default"><!--header-one-->
			<div class="container">
				<div class="nav navbar-nav wow fadeInLeft animated" data-wow-delay=".5s">
					@if (Auth::guest())
					<p>Welcome to {{ config('app.name') }} <a href="{{ route('register') }}">Register </a> Or <a href="{{ route('login') }}">Sign In</a></p>

					@else
					<p>Welcome to {{ config('app.name') }} {{ Auth::user()->name }}
					<a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Log Out <i class="fa fa-sign-out"></i> 
					</a>
					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
						{{ csrf_field() }}
					</form>     
					</p>
					@endif
				</div>
				<div class="nav navbar-nav navbar-right social-icons wow fadeInRight animated" data-wow-delay=".5s">
					<ul>
						<li><a href="#"></a></li>
						<li><a href="#" class="in"> </a></li>
						<li><a href="#" class="you"> </a></li>						
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="header-two navbar navbar-default"><!--header-two-->
			<div class="container">
				<div class="nav navbar-nav header-two-left">
					<ul>
						<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+9881100080</li>
						<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:littlejamun@gmail.com">littlejamun@gmail.com</a></li>			
					</ul>
				</div>
				<div class="nav navbar-nav logo wow zoomIn animated" data-wow-delay=".7s">
					<a href="{{ route('home') }}"><img src="{{ asset('images/logo.png') }}" width="250px"></a>
				</div>
				<div class="nav navbar-nav navbar-right header-two-right">
					<div class="header-right my-account">
						<a href="{{ route('shop.contact') }}"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> CONTACT US</a>						
					</div>
					<div class="header-right cart">
						<a href="#"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a>
						<h4><a href="{{ route('shop.cart') }}">
							<span class="simpleCart_total"> $0.00 </span> (<span id="simpleCart_quantity" class="simpleCart_quantity"> 0 </span>) 
						</a></h4>
						<div class="cart-box">
							<p><a href="javascript:;" class="simpleCart_empty">Empty cart</a></p>
							<div class="clearfix"> </div>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="top-nav navbar navbar-default"><!--header-three-->
			<div class="">
				<nav class="navbar" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<!--navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav top-nav-info">
							<li><a href="{{ route('home') }}" class="{{ $catId or 'active' }}">Home</a></li>
							@php
							$cats = App\Models\Category::get();
							@endphp
							@if ($cats->count())
							@forelse ($cats as $cat)
							@if ($cat->subCategory->count())

							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" class="{{ isset($catId) ? ($catId == $cat->cat_id ? 'active' : '') : '' }}" >{{ $cat->cat_name }}<b class="caret"></b></a>
								<ul class="dropdown-menu multi-column multi-column1">
									@forelse ($cat->subCategory()->get() as $scat)
									<li><a class="list" href="{{ route('shop.products',['cat' => $cat->cat_id, 'sub' => $scat->sc_id]) }}">{{ $scat->sc_name }}</a></li>
									@empty										
									@endforelse
								</ul>
							</li>	
							@else
							<li><a href="{{ route('shop.products',['cat' => $cat->cat_id]) }}"  class="{{ isset($catId) ? ($catId == $cat->cat_id ? 'active' : '') : '' }}">{{ $cat->cat_name }}</a></li>
							@endif
							@empty
							@endforelse
							
							@endif
							
							{{-- <li><a href="codes.html">Special Offers</a></li> --}}
						</ul> 
						<div class="clearfix"> </div>
						<!--//navbar-collapse-->
						<header class="cd-main-header">
							<ul class="cd-header-buttons">
								<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
							</ul> <!-- cd-header-buttons -->
						</header>
					</div>
					<!--//navbar-header-->
				</nav>
				<div id="cd-search" class="cd-search">
					<form method="get" action="{{ route('shop.search') }}">
						<input type="search" placeholder="Search..." name="search">
					</form>
				</div>
			</div>
		</div>
	</div>
	<!--//header-->

laravel/resources/views/user-panel/layouts/master.blade.php
@include('user-panel.layouts.header')
@yield('content')
@include('user-panel.layouts.footer')