laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop','as' => 'shop.'],function(){
		
	Route::get('/sub-categories/{id}', function ($id) {	
		return view('user-panel.sub-categories')->with(['catId' => $id]);
	})->name('our-menu');

	// Route::get('/sub-categories/{id}/{catId}', function ($id, $catId) {
	// 	return view('user-panel.sub-categories')->with(['subId' => $id, 'catId' => $catId]);
	// })->name('sub-menu');
	
	// Route::get('/child-categories/{id}/{subId}/{catId}', function ($id, $subId, $catId) {
	// 	return view('user-panel.child-categories')->with(['childId' => $id, 'subId' => $subId, 'catId' => $catId]);
	// })->name('child-menu');
	
	Route::get('/products/{cat}/{sub?}', 'ProductController@allProducts')->name('products');

	Route::get('/product/{id}','ProductController@show')->name('product');
	
	Route::get('/faq','FaqController@all')->name('faq');

	Route::get('/cart', function () {
		return view('user-panel.cart');
	})->name('cart');

	Route::get('/contact-us', function () {
		return view('user-panel.contact-us');
	})->name('contact');
	// Route::post('/contact', 'HomeController@contact')->name('add.contact');
	Route::get('/detail/{type}', 'HomeController@webDetails')->name('web-detail');

	Route::get('/our-story', function () {
		return view('user-panel.about');
	})->name('about');

	// Route::get('/terms', function () {
	// 	return view('user-panel.terms');
	// });

	Route::get('/search', 'ProductController@search')->name('search');
	
	Route::get('/offers', 'ProductController@offers')->name('offers');

	Route::post('/checkout','OrderController@checkout')->name('checkout');

	Route::post('/placeorder','OrderController@getPay')->name('placeorder');	

	Route::post('/paystatus','OrderController@orderStatus')->name('orderStatus');

	Route::resource('enquiry', 'EnquiryController');
	


	Route::post('fin-pin','PinCodeController@finPincode')->name('find-pin');

	Route::get('custom/{id}','OrderController@custom')->name('custom');
	
	Route::post('custom-enquiry','CustomEnquiryController@store')->name('store.custom');

	Route::get('/booked/order/{id}/{status?}', 'OrderController@previous')->name('previous');

});

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){
	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/form', function() {
		return view('admin.form');
	});
	Route::get('/table', function() {
		return view('admin.table');
	});

	Route::get('fetch-images/{id}','ProductController@images')->name('images');
	Route::resource('product', 'ProductController');
	Route::get('/detail', 'HomeController@view')->name('web-detail.index');
	Route::post('/detail', 'HomeController@update')->name('web-detail');
	
	// Route::resource('flavor', 'FlavorController');
	Route::resource('faq', 'FaqController');
	Route::resource('category', 'CategoryController');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('material', 'MaterialController');
	Route::resource('type-detail', 'TypeDetailController');
	Route::resource('color', 'ColorController');
	// Route::resource('child-category', 'ChildCategoryController');
	// Route::resource('super-child-category', 'SuperChildCategoryController');
	Route::resource('pincode','PinCodeController');	
	// Route::resource('testimonial', 'TestimonialController');
	// Route::resource('client', 'ClientController');
	Route::resource('banner', 'BannerController');
	Route::resource('second-banner', 'SecondBannerController');
	// Route::resource('offer', 'OfferController');
	// Route::resource('occasion', 'OccasionController');
	Route::resource('order', 'OrderController');
	Route::resource('enquiry', 'EnquiryController');
	// Route::resource('custom-enquiry', 'CustomEnquiryController');
	Route::post('send-enquiry', 'EnquiryController@send')->name('enquiry.send');
	// Route::post('send-custom-enquiry', 'CustomEnquiryController@send')->name('custom-enquiry.send');
	
	// Route::get('demo', 'CustomEnquiryController@demo');
	// Route::post('get-product', 'ProductController@getProduct')->name('get-product');
	
	Route::get('sub-categories/{id?}', 'SubCategoryController@getSubCategories')->name('getSubCategories');
	Route::post('fetch-types', 'TypeController@fetchTypes')->name('fetch-types');	
	Route::get('invoice/{id}', 'OrderController@invoice')->name('order-invoice');
	
	Route::get('fetch-all-images','ImportController@images')->name('all-images');	
	Route::get('import/', 'ImportController@import')->name('import-product');
	Route::post('upload-excel/', 'ImportController@uploadFile')->name('upload-excel');
	Route::post('import/', 'ImportController@importData')->name('import');
	Route::get('stock', 'ProductController@stock')->name('stock');
	
});



Route::get('/drop', ['as' => 'upload', 'uses' => 'ImageController@getUpload']);

Route::get('/drop2', function(){
	return view('admin.drop2');
});

Route::get('file-upload', 'JqueryController@index');
Route::post('file-upload', 'JqueryController@store')->name('file-upload');

Route::post('upload', ['as' => 'upload-post', 'uses' =>'ImageController@postUpload']);
Route::post('upload/delete', ['as' => 'upload-remove', 'uses' =>'ImageController@deleteUpload']);

laravel/resources/views/admin/create_client.blade.php
@extends('admin.layouts.master')
@section('title')
Create Client
@endsection

@php
	$ID = 'client';
@endphp
@push('header')
<script>
	ID = '{{ $ID }}';
</script>
@endpush
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Create New Client</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					<br />
					<form id = "{{ $ID }}Form" class="form-horizontal form-label-left" enctype="multipart/form-data">
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Company Name
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="text" class="form-control col-md-7 col-xs-12" name = "company">
							</div>
						</div>						
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">Display Picture
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">								
								<input type="file" class="form-control col-md-7 col-xs-12" name = "picture">
							</div>
						</div>						
						<div class="ln_solid">
						</div>
						<div class="form-group text-center">							
							<button type="submit" class="btn btn-success">Add
							</button>							
						</div>					
					</form>					
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@push('footer')
<script>
	CRUD.formSubmission({
		url : "{{ route('admin.'.$ID.'.store') }}", 
		type : 0,
		id : '{{ $ID }}Form'
	});		
</script>
@endpush

laravel/resources/views/admin/form.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
				<h3>Form Elements</h3>
			</div>

			<div class="title_right">
				<div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search for...">
						<span class="input-group-btn">
							<button class="btn btn-default" type="button">Go!</button>
						</span>
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Form Design <small>different form elements</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="#">Settings 1</a>
									</li>
									<li><a href="#">Settings 2</a>
									</li>
								</ul>
							</li>
							<li><a class="close-link"><i class="fa fa-close"></i></a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<br />
						<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">First Name <span class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Last Name <span class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
								</div>
							</div>
							<div class="form-group">
								<label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name / Initial</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div id="gender" class="btn-group" data-toggle="buttons">
										<label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
											<input type="radio" name="gender" value="male"> &nbsp; Male &nbsp;
										</label>
										<label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
											<input type="radio" name="gender" value="female"> Female
										</label>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required" type="text">
								</div>
							</div>
							<div class="ln_solid"></div>
							<div class="form-group">
								<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
									<button class="btn btn-primary" type="button">Cancel</button>
									<button class="btn btn-primary" type="reset">Reset</button>
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div>
		

		@endsection

laravel/resources/views/admin/image_upload.blade.php
@extends('admin.layouts.master')
@section('title')
Create New Category
@endsection
@php
$ID = 'category';
@endphp
@push('header')
<script>
	ID = '{{ $ID }}';
</script>
@endpush
@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
				<h3>Image Upload </h3>
			</div>

			<div class="title_right">
				<div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search for...">
						<span class="input-group-btn">
							<button class="btn btn-default" type="button">Go!</button>
						</span>
					</div>
				</div>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Dropzone multiple file uploader</h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="#">Settings 1</a>
									</li>
									<li><a href="#">Settings 2</a>
									</li>
								</ul>
							</li>
							<li><a class="close-link"><i class="fa fa-close"></i></a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<p>Drag multiple files to the box below for multi upload or click to select files. This is for demonstration purposes only, the files are not uploaded to any server.</p>
						<form action="form_upload.html" class="dropzone"></form>
						<br />
						<br />
						<br />
						<br />
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /page content -->
@endsection

@push('footer')
<script>	
	CRUD.formSubmission("{{ route('category.store') }}", 0,{'empty' : 'typeName'});
</script>
@endpush

laravel/resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/fav.png') }}"> 

  <title>{{ config('app.name') }} (Admin)</title>

  <!-- Bootstrap -->
  <link href="{{ asset('admin-assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('admin-assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('admin-assets/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- Animate.css -->
  <link href="{{ asset('admin-assets/animate.css/animate.min.css') }}" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="{{ asset('admin-assets/css/custom.min.css') }}" rel="stylesheet">
</head>

<body class="login">
  <div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form class="form-horizontal" method="POST" action="{{ route('login') }}">
              {{ csrf_field() }}
            <h1>Admin Login</h1>
            <div>
              <input placeholder="Email" id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

              @if ($errors->has('email'))
                  <span class="help-block">
                      <strong>{{ $errors->first('email') }}</strong>
                  </span>
              @endif              
            </div>
            <div>
              <input placeholder="Password" id="password" type="password" class="form-control" name="password" required>

              @if ($errors->has('password'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
              @endif              
            </div>
            <div>
              <button class="btn btn-default submit">Log in</button>
              <a class="reset_pass" href="#">Lost your password?</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
              {{-- <p class="change_link">New to site?
                <a href="#signup" class="to_register"> Create Account </a>
              </p> --}}

              <div class="clearfix"></div>
              <br />

              <div class="text-center">
                <img src="{{ asset('images/logo-black.png') }}" width="100%">
              </div>
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
</body>
</html>

laravel/resources/views/admin/view_banners.blade.php
@extends('admin.layouts.master')

@section('title')
Banners
@endsection
@push('header')
<!-- Datatables -->
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@php
$ID = 'banner';
@endphp
<script>
  var ID = '{{ $ID }}';
</script>
@endpush

@section('content')

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Banners</h3>
      </div>
      <div class="title_right">
        <button class="btn btn-primary pull-right" onclick="CRUD.add('{{ $ID }}','{{ route('admin.'.$ID.'.store') }}');">Add</button>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">            
            <table id="{{ $ID }}Table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>Image</th>
                  <th>Title</th>                  
                  <th>Sub Title</th>                  
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($banners as $k => $ban)
                <tr id = "tr-{{ $ban->ban_id }}">
                  <td>{{ ++$k }}</td>
                  <td><img src="{{ asset($ban->ban_img_path) }}" class="pro-img"></td>
                  <td>{{ str_limit($ban->ban_title, 30) }}</td>                  
                  <td>{{ str_limit($ban->ban_sub_title, 30) }}</td>                  
                  <td>                    
                    <a href="#" class="btn btn-info btn-xs" onclick = "$(this).CRUD({url : '{{ route('admin.'.$ID.'.index') }}',fetchId:'{{ $ban->ban_id }}',id : '{{ $ID }}'}, 'edit')"><i class="fa fa-pencil"></i> Edit</a>                    
                    <a onclick = "CRUD.delete('{{ $ID }}',{{ $ban->ban_id }});" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>                    
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan = "4" class="text-center">No {{ $ID }} Found <a class = "btn btn-primary" href="{{ route('admin.'.$ID.'.create') }}">Add some now</a></td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>


    <div class="modal fade" id="{{ $ID }}Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="{{ $ID }}ModalLabel">Edit {{ $ID }}</h4>
          </div>
          <div class="modal-body">
            @include('admin.forms.banner_form')                        
            {{-- <form id = "{{ $ID }}Form" class="form-horizontal form-label-left">
              <input type="hidden" name="sid">              
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Title
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">               
                  <input type="text" class="form-control col-md-7 col-xs-12" name = "title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Sub Title
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">               
                  <input type="text" class="form-control col-md-7 col-xs-12" name = "sub_title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Upload Banner
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">               
                  <input type="file" class="form-control col-md-7 col-xs-12" name = "banner_img">
                </div>
              </div>
              <div class="ln_solid">
              </div>
              <div class="form-group text-center">              
                <button type="submit" class="btn btn-success">Update
                </button>             
              </div>          
            </form>  --}}           
          </div>          
        </div>
      </div>
    </div>

    <div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Are You Sure?</h4>
            <br>
            <div>
              <form id = "{{ $ID }}DForm">                
                <button type = "button" class="btn btn-danger" id = "yes">Yes</button>
                <button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
              </form>
            </div>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
{{-- <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script> --}}
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript">  
  var update = "{{ url('admin/'.$ID) }}",
  deleteU = "{{ url('admin/'.$ID) }}",
  store = "{{ route('admin.'.$ID.'.store') }}";

  Table.init(ID);

  $('#{{ $ID }}Form').CRUD({
    url : '{{ route('admin.'.$ID.'.store') }}',
    validation:false, 
    processResponse : function (data) {      
    }
  });
</script>
@endpush