laravel/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop','as' => 'shop.'],function(){
		
	Route::get('/sub-categories/{id}', function ($id) {	
		return view('user-panel.sub-categories')->with(['catId' => $id]);
	})->name('our-menu');

	// Route::get('/sub-categories/{id}/{catId}', function ($id, $catId) {
	// 	return view('user-panel.sub-categories')->with(['subId' => $id, 'catId' => $catId]);
	// })->name('sub-menu');
	
	// Route::get('/child-categories/{id}/{subId}/{catId}', function ($id, $subId, $catId) {
	// 	return view('user-panel.child-categories')->with(['childId' => $id, 'subId' => $subId, 'catId' => $catId]);
	// })->name('child-menu');
	
	Route::get('/products/{cat}/{sub?}', 'ProductController@allProducts')->name('products');

	Route::get('/product/{id}','ProductController@show')->name('product');
	
	Route::get('/faq','FaqController@all')->name('faq');

	Route::get('/cart', function () {
		return view('user-panel.cart');
	})->name('cart');

	Route::get('/contact-us', function () {
		return view('user-panel.contact-us');
	})->name('contact');
	// Route::post('/contact', 'HomeController@contact')->name('add.contact');
	Route::get('/detail/{type}', 'HomeController@webDetails')->name('web-detail');

	Route::get('/our-story', function () {
		return view('user-panel.about');
	})->name('about');

	// Route::get('/terms', function () {
	// 	return view('user-panel.terms');
	// });

	Route::get('/search', 'ProductController@search')->name('search');
	
	Route::get('/offers', 'ProductController@offers')->name('offers');

	Route::post('/checkout','OrderController@checkout')->name('checkout');

	Route::post('/placeorder','OrderController@getPay')->name('placeorder');	

	Route::post('/paystatus','OrderController@orderStatus')->name('orderStatus');

	Route::resource('enquiry', 'EnquiryController');
	


	Route::post('fin-pin','PinCodeController@finPincode')->name('find-pin');

	Route::get('custom/{id}','OrderController@custom')->name('custom');
	
	Route::post('custom-enquiry','CustomEnquiryController@store')->name('store.custom');

	Route::get('/booked/order/{id}/{status?}', 'OrderController@previous')->name('previous');

});

Route::get('/admin/login', function() {
	return view('admin.login');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){
	
	Route::get('/', function() {
		return view('admin.dashboard');
	})->name('home');
	
	Route::get('/form', function() {
		return view('admin.form');
	});
	Route::get('/table', function() {
		return view('admin.table');
	});

	Route::get('fetch-images/{id}','ProductController@images')->name('images');
	Route::resource('product', 'ProductController');
	Route::get('/detail', 'HomeController@view')->name('web-detail.index');
	Route::post('/detail', 'HomeController@update')->name('web-detail');
	
	// Route::resource('flavor', 'FlavorController');
	Route::resource('faq', 'FaqController');
	Route::resource('category', 'CategoryController');
	Route::resource('sub-category', 'SubCategoryController');
	Route::resource('material', 'MaterialController');
	Route::resource('type-detail', 'TypeDetailController');
	Route::resource('color', 'ColorController');
	// Route::resource('child-category', 'ChildCategoryController');
	// Route::resource('super-child-category', 'SuperChildCategoryController');
	Route::resource('pincode','PinCodeController');	
	// Route::resource('testimonial', 'TestimonialController');
	// Route::resource('client', 'ClientController');
	Route::resource('banner', 'BannerController');
	Route::resource('second-banner', 'SecondBannerController');
	// Route::resource('offer', 'OfferController');
	// Route::resource('occasion', 'OccasionController');
	Route::resource('order', 'OrderController');
	Route::resource('enquiry', 'EnquiryController');
	// Route::resource('custom-enquiry', 'CustomEnquiryController');
	Route::post('send-enquiry', 'EnquiryController@send')->name('enquiry.send');
	// Route::post('send-custom-enquiry', 'CustomEnquiryController@send')->name('custom-enquiry.send');
	
	// Route::get('demo', 'CustomEnquiryController@demo');
	// Route::post('get-product', 'ProductController@getProduct')->name('get-product');
	
	Route::get('sub-categories/{id?}', 'SubCategoryController@getSubCategories')->name('getSubCategories');
	Route::post('fetch-types', 'TypeController@fetchTypes')->name('fetch-types');	
	Route::get('invoice/{id}', 'OrderController@invoice')->name('order-invoice');
	
	Route::get('fetch-all-images','ImportController@images')->name('all-images');	
	Route::get('import/', 'ImportController@import')->name('import-product');
	Route::post('upload-excel/', 'ImportController@uploadFile')->name('upload-excel');
	Route::post('import/', 'ImportController@importData')->name('import');
	Route::get('stock', 'ProductController@stock')->name('stock');
	
});



Route::get('/drop', ['as' => 'upload', 'uses' => 'ImageController@getUpload']);

Route::get('/drop2', function(){
	return view('admin.drop2');
});

Route::get('file-upload', 'JqueryController@index');
Route::post('file-upload', 'JqueryController@store')->name('file-upload');

Route::post('upload', ['as' => 'upload-post', 'uses' =>'ImageController@postUpload']);
Route::post('upload/delete', ['as' => 'upload-remove', 'uses' =>'ImageController@deleteUpload']);

laravel/app/Http/Controllers/UserPanel/ProductController.php
<?php

namespace App\Http\Controllers\UserPanel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/user-panel/cart.blade.php
@extends('user-panel.layouts.master')
@section('title')
	Cart
@endsection
@section('content')
<!--breadcrumbs-->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Check Out page</li>
		</ol>
	</div>
</div>
<!--//breadcrumbs-->
<!--cart-items-->
<div class="cart-items">
	<div class="container">
		<h3 class="wow fadeInUp animated" data-wow-delay=".5s">Shopping Cart Details</h3>
		<div class="simpleCart_items table-content table-responsive"></div>
		<div class="row">
			<div class="col-md-8 col-sm-7 col-xs-12">						
				<div class="coupon">
					<h3></h3>
					<p>Enter your pin code, for delivery.</p>
					<form id = "pinForm">								
						<input type="text" placeholder="Pin Code" autocomplete="off" autocomplete = "off" name = "pincode" id = "pincode" />
						<input type="submit" value="Check Availability" />
					</form>
					<div class="clearfix"></div>
					<p id = "pinMsg" class="hidden"></p>
					<p id = "pinStatus" class="hidden">0</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-5 col-xs-12">
				<div class="cart_totals">
					<h2>Cart Totals</h2>
					<div class="clearfix"></div>
					<table>
						<tbody>
							<tr class="cart-subtotal">
								<th>Subtotal</th>
								<td><span class="amount simpleCart_total"></span></td>
							</tr>
							<tr class="shipping">
								<th>Shipping</th>
								<td>												
									<span class="simpleCart_shipping"></span>
								</td>
							</tr>
							<tr class="order-total">
								<th>Total</th>
								<td>
									<strong><span class="amount simpleCart_grandTotal" id = "finalGrand">&#8377;</span></strong>
									{{-- <span class="simpleCart_grandTotal hidden" id = "grand"></span> --}}
								</td>
							</tr>											
						</tbody>
					</table>
					<div class="wc-proceed-to-checkout">
						<a href="javascript:;" class="simpleCart_checkout">Proceed to Checkout</a>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>
<!--//cart-items-->	
@endsection

@push('footer')
<script type="text/javascript">		
	simpleCart({	    
		shippingFlatRate:0,
		cartStyle: "table",
		cartColumns: [
		{ view: function( item, column) {
			// console.log(column);
			return '<a href="'+item.get('pagelink')+'"><img src="'+item.get('thumb')+'" alt="" width = "100" class = "cart-img"/></a>';			
		}, label: 'Image', attr:'thumb' },		
		{ attr: "name", label: "Product Name" , view : function(item, column){
			return '<span class ="">'+item.get('name')+'</span>';
		}},
		{ label: 'Text' , view: function(item, column){			
			return (typeof item.get('text') !== "undefined") ? '"'+item.get('text')+'"' : "-" ;
		}},
		{ attr: "price" , label: "Price", view: function(item, column){			
			return '<span class="amount"> &#8377;'+item.get('price')+'</span>';
		}},
		{ attr: "quantity" , label: "Qty" , className : "qty-width", view: function(item, column){
			return '<a href="javascript:;" class="simpleCart_decrement"><i class = "fa fa-minus"></i></a><span class = "spanQty">'+item.get('quantity')+'</span><a href="javascript:;" class="simpleCart_increment"><i class = "fa fa-plus"></i></a>';

		}},
		{ attr: "total" , label: "Total" , view: function (item, column) {
			if(item.get('pro')){
				return '<span id = "tot-'+item.get('pro')+'">&#8377;'+parseFloat(item.get('total')).toFixed(2)+'</span>';
			}else{
				return '<span id = "tot-'+item.get('offer')+'">&#8377;'+parseFloat(item.get('total')).toFixed(2)+'</span>';				
			}
		}},
		{ label: 'Ordered QTY' , attr: 'size', view: function(item, column){
				return '<span id = "qty-'+item.get('pro')+'">'+item.get('quantity')+'</span>';			
		}},
		{ view: "remove" , text: "<i class='fa fa-times-circle wrong-circle'></i>" , label: 'Remove'}
		],
		checkout: {
			type: "SendForm",
			url: "{{ route('shop.checkout') }}",
			method: "POST",
			extra_data: {
				grand : $('#finalGrand').html(),
				_token : $('meta[name="csrf-token"]').attr('content')
			}
		} 
	});	


	simpleCart.bind( 'beforeCheckout' , function( data ){
		// if(simpleCart.quantity() > 0){

			if($('#pincode').val() == ''){
				$('#pincode').focus();
				$('#pinMsg').removeClass('hidden').addClass('red').html('Please select Pincode for delivery');			
				return false;
			}

			if($('#pinStatus').html() == '1'){
				data.grand = $('.simpleCart_grandTotal').html();
				data.shipping = $('.simpleCart_shipping').html();
				data.pincode = $('#pincode').val();
				data._token = $('meta[name="csrf-token"]').attr('content');
			}else{
				return false;
			}
		// }else{
		// 	$('.simpleCart_checkout').hide();
		// }
	});

	function checkPin(fd) {
		$.ajax({
			url : '{{ route('shop.find-pin') }}',
			type : 'post',
			data : fd,
			processData: false,
			contentType : false,
			success : function(data){					
				if(data.msg == 'success'){
					$('#pinMsg').removeClass('hidden red').addClass('green').html('We are available to delivery at this pincode.');

					var pinPrice = parseFloat(data.data.pin_price), 
					grand = parseFloat($('.simpleCart_total').html().replace('₹', '').replace(',',''));
					var total = grand + pinPrice;

					$('.simpleCart_shipping').html('&#8377;'+data.data.pin_price+'.00');
					$('#finalGrand').html('&#8377;'+parseFloat(total)+'.00');
					$('#pinStatus').html('1');
				}else{
					$('#pinMsg').removeClass('hidden green').addClass('red').html('Sorry!! we cannot provide deivery to this pincode.');
					$('.simpleCart_shipping').html('&#8377;00.00');					
					$('#pinStatus').html('0');						
					// window.setTimeout(function() {
					// 	$('#pinMsg').addClass('hidden').html('');
					// },2000);
				}

			}
		});
	}
	$('#pinForm').on({
		'submit' : function(e){
			e.preventDefault();
			var fd = new FormData(this);
			checkPin(fd);			
		}
	});

	$('#pincode').on({
		'keyup change' : function(e){
			e.preventDefault();
			var fd = new FormData();
			fd.append('pincode', this.value);
			checkPin(fd);
		}
	});	
</script>
@endpush

laravel/resources/views/user-panel/contact-us.blade.php
@extends('user-panel.layouts.master')
@section('title')
	Contact Us
@endsection
@push('header')
	@php
		$ID = "enquiry";
	@endphp
	<script type="text/javascript">
		var ID = '{{ $ID }}';
	</script>
@endpush
@section('content')
<!--breadcrumbs-->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Contact Us</li>
		</ol>
	</div>
</div>
<!--//breadcrumbs-->
<!--contact-->
<div class="contact">
	<div class="container">
		<div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
			<h3 class="title">How To <span> Find Us</span></h3>
		</div>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3783.8525568654604!2d73.85161691520125!3d18.49033667492332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2c01b4c7f5f83%3A0xd15f6ec56a1be851!2sNescraft+Systems!5e0!3m2!1sen!2sin!4v1525895557204" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>	
</div>
<div class="address"><!--address-->
	<div class="container">
		<div class="address-row">
			<div class="col-md-6 address-left wow fadeInLeft animated" data-wow-delay=".5s">
				<div class="address-grid">
					<h4 class="wow fadeIndown animated" data-wow-delay=".5s">DROP US A LINE </h4>
					<form id = "{{ $ID }}Form">
						<input type="hidden" name="type" value="101">						
						<input name="name" id = "name" class="wow fadeIndown animated" data-wow-delay=".6s" type="text" placeholder="Name" required="">
						<input name="email" id = "email" class="wow fadeIndown animated" data-wow-delay=".7s" type="text" placeholder="Email" required="">
						<input name="mobile" id = "mobile" class="wow fadeIndown animated" data-wow-delay=".8s" type="text" placeholder="Mobile" required="">
						<textarea name="query" class="wow fadeIndown animated" data-wow-delay=".8s" placeholder="Message" required=""></textarea>
						<input class="wow fadeIndown animated" data-wow-delay=".9s" type="submit" value="SEND">
					</form>
				</div>
			</div>
			<div class="col-md-6 address-right">
				<div class="address-info wow fadeInRight animated" data-wow-delay=".5s">
					<h4>ADDRESS</h4>
					<p>
						Nescraft Systems,
						48A, Parvati Industrial Estate,
						Opp. Adinath Society,
						Pune-Satara Road,
						Pune-411009.</p>
				</div>
				<div class="address-info address-mdl wow fadeInRight animated" data-wow-delay=".7s">
					<h4>PHONE </h4>
					<p>+91 9881100080</p>
				</div>
				<div class="address-info wow fadeInRight animated" data-wow-delay=".6s">
					<h4>MAIL</h4>
					<p><a href="mailto:littlejamun@gmail.com"> littlejamun@gmail.com</a></p>
				</div>
			</div>
		</div>	
	</div>	
</div>
<!--//contact-->	
@endsection

@push('footer')
	<script type="text/javascript">
		CRUD.formSubmission({
			url : '{{ route('shop.enquiry.store') }}',
			id : 'enquiryForm',
			type : 0,
			validate : {'mobile' : 'mobile' , 'alphaSpace' : 'name', 'email' : 'email'}
		});
		// 
	</script>
@endpush

laravel/resources/views/user-panel/products.blade.php
@extends('user-panel.layouts.master')
@section('title')
    {{ \App\Models\Category::find($catId)->cat_name }} Products
@endsection
@push('header')
<link href="{{ asset('css/w3.css') }}" rel="stylesheet">
<link href="{{ asset('css/style2.css') }}" rel="stylesheet">    
@endpush
@section('content')
<!--breadcrumbs-->
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
            <li class="active">Products</li>
        </ol>
    </div>
</div>
<!--//breadcrumbs-->



<!--products-->
<div class="products">   
    <div class="container">
        <div class="col-md-12 product-model-sec">
            @php
            $k = 2;
            @endphp
            @forelse ($products as $pro)
            
            <div class="product-grids {{ ( $k % 3== 0) ? 'product-grids-mdl' : ''}} simpleCart_shelfItem wow fadeInUp animated" data-wow-delay=".5s">
                <div class="new-top">
                    <div class="selectProduct w3-padding" data-title="Nexus6P" data-id="Nexus 6P" data-size="5.7&quot;" data-weight="178 g" data-processor="1.55 GHz, Octa Core, Qualcomm Snapdragon 810 " data-battery="3450 mAH">
                        {{-- <a class="w3-btn-floating w3-light-grey addButtonCircular addToCompare">+</a> --}}
                        <img src="{{ asset(isset($pro->display) ? $pro->display->img_thumb_path : '') }}" alt="{{ $pro->pro_title }}" class="img-responsive product-img item_thumb"/>
                        <span class="item_pageLink hidden">{{ route('shop.product',['id' => $pro->pro_id]) }}</span>                            
                    </div>
                    <div class="new-text">
                        <ul>
                            <li><a href="{{ route('shop.product',['id' => $pro->pro_id]) }}">Quick View </a></li>
                            {{-- <li><input type="number" class="item_quantity" min="1" value="1" max = "{{ $pro->pro_qty }}"></li>
                            <li><a class="item_add" href="javascript:;"> Add to cart</a></li> --}}
                        </ul>
                    </div>
                </div>
                <div class="new-bottom">
                    <h5><a class="name item_name" title="{{ $pro->pro_title }}" href="{{ route('shop.product',['id' => $pro->pro_id]) }}">{{ str_limit($pro->pro_title, 20) }}</a></h5>                 
                    <div class="ofr">
                        @php
                        $r = $pro->pro_price;

                        if ($pro->pro_discount){
                            $r = $r - ($r * ($pro->pro_discount/100));
                        }
                        @endphp
                        @if ($pro->pro_discount)                        
                        <p class="pric1"><del>&#8377; {{ number_format($pro->pro_price,2) }}</del></p>
                        @endif
                        <p><span class="item_price">&#8377; {{ number_format($r,2) }}</span></p>
                        <div class="item_pro hidden">{{ $pro->pro_id }}</div>
                    </div>
                </div>
            </div>
            @php
            $k++;
            @endphp
            @empty
            No Product Found
            @endforelse         
        </div>
        
        <div class="clearfix"> </div>
    </div>
</div>
<!--//products-->



<!--preview panel-->
<div class="w3-container  w3-center">
    <div class="w3-row w3-card-4 w3-grey w3-round-large w3-border comparePanle w3-margin-top">
        <div class="w3-row">
            <div class="w3-col l9 m8 s6 w3-margin-top">
                <h4>Added for comparison</h4>
            </div>
            <div class="w3-col l3 m4 s6 w3-margin-top">
                &nbsp;
                <button class="w3-btn w3-round-small w3-white w3-border notActive cmprBtn" disabled>Compare</button>
            </div>
        </div>
        <div class=" titleMargin w3-container comparePan">
        </div>
    </div>
</div>
<!--end of preview panel-->

<!-- comparision popup-->
<div id="id01" class="w3-animate-zoom w3-white w3-modal modPos">
    <div class="w3-container">
        <a onclick="document.getElementById('id01').style.display='none'" class="whiteFont w3-padding w3-closebtn closeBtn">&times;</a>
    </div>
    <div class="w3-row contentPop w3-margin-top">
    </div>

</div>
<!--end of comparision popup-->

<!--  warning model  -->
<div id="WarningModal" class="w3-modal">
    <div class="w3-modal-content warningModal">
        <header class="w3-container w3-teal">
            <h3><span>&#x26a0;</span>Error</h3>
        </header>
        <div class="w3-container">
            <h4>Maximum of Four products are allowed for comparision</h4>

        </div>
        <footer class="w3-container w3-right-align">
            <button id="warningModalClose" onclick="document.getElementById('id01').style.display='none'" class="w3-btn w3-hexagonBlue w3-margin-bottom  ">Ok</button>
        </footer>
    </div>
</div>
<!--  end of warning model  -->


@endsection

@push('footer')
<script src="{{ asset('js/compare.js') }}"></script>
@endpush

laravel/resources/views/user-panel/sub-categories.blade.php
@extends('user-panel.layouts.master')
@section('title')
{{ \App\Models\Category::find($catId)->cat_name }} Products
@endsection
@push('header')
<link href="{{ asset('css/w3.css') }}" rel="stylesheet">
<link href="{{ asset('css/style2.css') }}" rel="stylesheet">	
@endpush
@section('content')
<!--breadcrumbs-->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Products</li>
		</ol>
	</div>
</div>
<!--//breadcrumbs-->



<!--products-->
<div class="products">	 
	<div class="container">
		<div class="col-md-12 product-model-sec">
			@php
			$k = 2;
			@endphp
			@forelse (\App\Models\SubCategory::where('sc_cat_id', $catId)->get() as $sub)
			
			<div class="product-grids {{ ( $k % 3== 0) ? 'product-grids-mdl' : ''}} simpleCart_shelfItem wow fadeInUp animated" data-wow-delay=".5s">
				<div class="new-top">
					<div class="selectProduct w3-padding" data-title="Nexus6P" data-id="Nexus 6P" data-size="5.7&quot;" data-weight="178 g" data-processor="1.55 GHz, Octa Core, Qualcomm Snapdragon 810 " data-battery="3450 mAH">
						<a href="{{ route('shop.products', ['sub' => $sub->sc_id, 'cat' => $catId]) }}">
							<img src="{{ asset($sub->sc_icon_path) }}" alt="{{ $sub->sc_name }}" class="img-responsive product-img item_thumb"/>							
						</a>						
					</div>					
				</div>
				<div class="new-bottom">
					<h5><a class="name item_name" title="{{ $sub->sc_name }}" href="{{ route('shop.products', ['sub' => $sub->sc_id, 'cat' => $catId]) }}">{{ str_limit($sub->sc_name, 20) }}</a></h5>					
				</div>
			</div>
			@php
			$k++;
			@endphp
			@empty
			No Sub Categories Found
			@endforelse			
		</div>
		
		<div class="clearfix"> </div>
	</div>
</div>
<!--//products-->
@endsection

@push('footer')
<script src="{{ asset('js/compare.js') }}"></script>
@endpush